name: bot

on:
  workflow_dispatch:
    inputs:
      pr_title:
        description: 'Title of the Pull Request'
        required: true
        default: '[BOT] Bump locks'

jobs:
  update-locks:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - { branch_name: 'update_xc7', env_yml: 'xc7/environment.yml', conda_lock: 'xc7/conda_lock.yml' }
          - { branch_name: 'update_eos-s3', env_yml: 'eos-s3/environment.yml', conda_lock: 'eos-s3/conda_lock.yml' }
    env:
      BOT_BRANCH:     ${{ matrix.branch_name }}_${{ github.run_id }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules:  'recursive'

    - name: Run Action
      uses: ./.github/bot
      with:
        branch_name:      ${{ matrix.branch_name }}
        environment_file: ${{ matrix.env_yml }}
        conda_lock_file:  ${{ matrix.conda_lock }}

    - name: Create A Pull Request
      uses: actions/github-script@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.pulls.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            head: `${process.env.BOT_BRANCH}`,
            base: "master",
            title: `${{ github.event.inputs.pr_title }}`,
          })
