name: bot

on:
  workflow_dispatch:
    inputs:
      bot_rev_and_path:
        description: 'Revision and path of the bot script (GIT_REV/PATH/TO/bot.py)'
        required: true
        default: 'master/.github/scripts/bot.py'

jobs:
  update-locks:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - { branch: 'update_locks', env_yml: 'xc7/environment.yml', lockfile: 'xc7/conda.lock', pr_base: 'master' }

    env:
      BOT_BRANCH:   ${{ matrix.branch }}
      BOT_ENV_YML:  ${{ matrix.env_yml }}
      BOT_LOCKFILE: ${{ matrix.lockfile }}
      BOT_PR_BASE:  ${{ matrix.pr_base }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Activate Conda Base Environment
      run: |
        which conda
        which python3
        python3 -V
        python3 -m pip list
        eval "$('conda' 'shell.bash' 'hook' 2>/dev/null)"
        which conda
        which python3
        python3 -V
        python3 -m pip list

    - name: Check Environment
      run: |
        echo "GITHUB_ACTION: $GITHUB_ACTION"
        echo "BOT_BRANCH: $BOT_BRANCH"
        echo "BOT_ENV_YML: $BOT_ENV_YML"
        echo "BOT_LOCKFILE: $BOT_LOCKFILE"
        echo "BOT_PR_BASE: $BOT_PR_BASE"
        which conda
        which python3
        conda env list
        python3 -m pip list

    - name: Gather Dependencies
      run: |
        #python3 -m pip install setuptools
        python3 -m pip install pygithub
        wget https://raw.githubusercontent.com/antmicro/symbiflow-examples-bot/${{ github.event.inputs.bot_rev_and_path }}

    - name: Update Lock And Create Pull Request
      run: |
        ls -l
        echo "BOT_BRANCH: $BOT_BRANCH"
        echo "BOT_ENV_YML: $BOT_ENV_YML"
        echo "BOT_LOCKFILE: $BOT_LOCKFILE"
        echo "BOT_PR_BASE: $BOT_PR_BASE"
        python3 bot.py
        ls -l ..
