name: bot

on:
  workflow_dispatch:
    inputs:
      bot_rev_and_path:
        description: 'Revision and path of the bot script (GIT_REV/PATH/TO/bot.py)'
        required: true
        default: 'master/.github/scripts/bot.py'

jobs:
  update-locks:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - { branch: 'update_locks', env_yml: 'xc7/environment.yml', conda_lock: 'xc7/conda.lock', pip_lock: 'xc7/pip.lock', pr_base: 'master' }

    env:
      BOT_BRANCH:     ${{ matrix.branch }}
      BOT_ENV_YML:    ${{ matrix.env_yml }}
      BOT_CONDA_LOCK: ${{ matrix.conda_lock }}
      BOT_PIP_LOCK:   ${{ matrix.pip_lock }}
      BOT_PR_BASE:    ${{ matrix.pr_base }}
      GITHUB_TOKEN:   ${{ github.token }}

    steps:
    - name: Check environment
      run: |
        echo "::group::Check git"
        which git
        git --version
        echo "::endgroup::"
        echo "::group::Check conda"
        which conda
        conda -V
        echo
        echo "Packages in the current environment:"
        conda list
        echo "::endgroup::"
        echo "::group::Check python"
        which python3
        python3 -V
        echo
        echo "Python modules installed in pip:"
        python3 -m pip list
        echo "::endgroup::"

    - name: Gather dependencies
      run: |
        python3 -m pip install setuptools
        python3 -m pip install pygithub
        wget https://raw.githubusercontent.com/antmicro/symbiflow-examples-bot/${{ github.event.inputs.bot_rev_and_path }}

    - name: Update Lock And Create Pull Request
      run: |
        echo "GITHUB_RUN_ID: $GITHUB_RUN_ID"
        echo "GITHUB_RUN_NUMBER: $GITHUB_RUN_NUMBER"
        python3 bot.py
