name: update_conda_locks

on:
  push:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: '0 3 * * *'

jobs:
  update-locks:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - { branch_name: 'pre-merge-test_xc7', env_yml: 'xc7/environment.yml', conda_lock: 'xc7/conda_lock.yml', pr_base: 'symbiflow-examples-master', pr_title: '[PRE-MERGE TEST] Bump xc7 lock' }
          - { branch_name: 'pre-merge-test_eos-s3', env_yml: 'eos-s3/environment.yml', conda_lock: 'eos-s3/conda_lock.yml', pr_base: 'symbiflow-examples-master', pr_title: '[PRE-MERGE TEST] Bump eos-s3 lock' }
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules:  'recursive'
        ref:         ${{ matrix.pr_base }}

    - name: Update Lock and Issue a Pull Request
      uses: antmicro/actions/update_conda_lock@9fddb03ca16c65940b8b6f422da06a17101e3c9e
      with:
        branch_name_core: ${{ matrix.branch_name }}
        conda_lock_file:  ${{ matrix.conda_lock }}
        environment_file: ${{ matrix.env_yml }}
        gh_access_token:  ${{ secrets.GITHUB_TOKEN }}
        pr_title_core:    ${{ matrix.pr_title }}
